[package]
name = "backend"
version = "0.1.0"
authors = ["Tiffany Bennett <tiffany@stormbit.net>"]

[dependencies]
atom_syndication = "0.5"
chrono = "0.4"
websocket = "0.20.2"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"

[dependencies.rusqlite]
version = "0.13.0"
features = [ "bundled" ]
